name: Il mio primo GitHub Action
on:
  push:
jobs:
  italian-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - run: sudo apt update
      - run: pwd
      - run: touch hello.txt
      - run: ls -a
      - run: java --version
      - run: cd template-progetto
      - run: ls
      - run: pwd
        working-directory: template-progetto
      - run: mvn install
        working-directory: template-progetto
